### ISSUE TITLE
Add nosym=true for MD.

### ISSUE THREAD

**Issue by ZGainsforth** [quantumVITAS/quantumVITAS#3]
There doesn't seem to be a way to turn symmetry off when doing MD calculations.  I ran a 2x2x2 superlattice of the spinel primitive cell with MD but it failed to work because of symmetry.  By manually editing the in file and adding nosym=.true. it worked fine.  I would recommend adding nosym=.true. by default for MD.  

Here is the BOMD.in file that worked (exactly as generated by QV, but with the added nosym line):

`!BOMD
&CONTROL  
outdir='.\outdir'
calculation='md'
pseudo_dir='C:/Program Files/quantumVITAS-0.2.0_windows/pseudoPotLibs/SSSP_v1.1/SSSP_efficiency'
/
&SYSTEM  
ibrav=14
A=11.555133938979552
B=11.555133938979552
C=11.555133938979552
cosBC=0.5000000000000001
cosAC=0.5000000000000001
cosAB=0.4999999999999999
nosym=.true.
nat=112
ntyp=3
ecutwfc=30.0
occupations='smearing'
degauss=0.003
smearing='gaussian'
/
&ELECTRONS  
/
&IONS  
ion_temperature='andersen'
/
ATOMIC_SPECIES  
Al  26.98153843  Al.pbe-n-kjpaw_psl.1.0.0.UPF
Mg  24.305  Mg.pbe-n-kjpaw_psl.0.3.0.UPF
O  15.999  O.pbe-n-kjpaw_psl.0.1.UPF

ATOMIC_POSITIONS (crystal) 
Al  0.5  0.0  0.0  1  1  1
Al  0.0  0.5  0.0  1  1  1
Al  0.0  0.5  0.5  1  1  1
Al  0.0  0.0  0.5  1  1  1
Al  0.5  0.0  0.5  1  1  1
Al  0.5  0.5  0.0  1  1  1
Al  -0.0  -0.0  0.0  1  1  1
Al  0.751594744  0.500883615  0.500883615  1  1  1
Al  0.749982549  0.4999963  0.999878294  1  1  1
Al  0.250013587  0.999941788  0.999941788  1  1  1
Al  0.250017451  1.20706E-4  0.5000017  1  1  1
Al  0.250017451  0.5000017  1.20706E-4  1  1  1
Al  0.248405256  0.499115385  0.499115385  1  1  1
Al  0.749986413  5.8212E-5  5.8212E-5  1  1  1
Al  0.749982549  0.999878294  0.4999963  1  1  1
Al  0.4999963  0.749982549  0.999878294  1  1  1
Al  0.999941788  0.250013587  0.999941788  1  1  1
Al  1.20706E-4  0.250017451  0.5000017  1  1  1
Al  5.8212E-5  0.749986413  5.8212E-5  1  1  1
Al  0.999878294  0.749982549  0.4999963  1  1  1
Al  0.5000017  0.250017451  1.20706E-4  1  1  1
Al  0.499115385  0.248405256  0.499115385  1  1  1
Al  0.500883615  0.751594744  0.500883615  1  1  1
Al  0.999878294  0.4999963  0.749982549  1  1  1
Al  0.999941788  0.999941788  0.250013587  1  1  1
Al  5.8212E-5  5.8212E-5  0.749986413  1  1  1
Al  1.20706E-4  0.5000017  0.250017451  1  1  1
Al  0.5000017  1.20706E-4  0.250017451  1  1  1
Al  0.4999963  0.999878294  0.749982549  1  1  1
Al  0.499115385  0.499115385  0.248405256  1  1  1
Al  0.500883615  0.500883615  0.751594744  1  1  1
Al  0.5  0.5  0.5  1  1  1
Mg  0.687906933  0.687906933  0.186546991  1  1  1
Mg  0.187516675  0.187516675  0.187516675  1  1  1
Mg  0.18753404  0.18753404  0.687450412  1  1  1
Mg  0.18753404  0.687450412  0.18753404  1  1  1
Mg  0.186546991  0.687906933  0.687906933  1  1  1
Mg  0.687450412  0.18753404  0.18753404  1  1  1
Mg  0.687906933  0.186546991  0.687906933  1  1  1
Mg  0.688175889  0.688175889  0.688175889  1  1  1
Mg  0.81246496  0.81246496  0.312549588  1  1  1
Mg  0.311822111  0.311822111  0.311822111  1  1  1
Mg  0.312091067  0.312091067  0.813452009  1  1  1
Mg  0.312091067  0.813452009  0.312091067  1  1  1
Mg  0.312549588  0.81246496  0.81246496  1  1  1
Mg  0.813452009  0.312091067  0.312091067  1  1  1
Mg  0.81246496  0.312549588  0.81246496  1  1  1
Mg  0.812483325  0.812483325  0.812483325  1  1  1
O  0.617709591  0.118656892  0.617709591  1  1  1
O  0.118134815  0.118134815  0.118134815  1  1  1
O  0.118122666  0.118122666  0.618107378  1  1  1
O  0.118122666  0.618107378  0.118122666  1  1  1
O  0.619093966  0.619093966  0.619093966  1  1  1
O  0.118656892  0.617709591  0.617709591  1  1  1
O  0.618107378  0.118122666  0.118122666  1  1  1
O  0.617709591  0.617709591  0.118656892  1  1  1
O  0.380904034  0.380904034  0.380904034  1  1  1
O  0.382287409  0.382287409  0.881344108  1  1  1
O  0.382287409  0.881344108  0.382287409  1  1  1
O  0.381890622  0.881877334  0.881877334  1  1  1
O  0.881344108  0.382287409  0.382287409  1  1  1
O  0.881877334  0.381890622  0.881877334  1  1  1
O  0.881877334  0.881877334  0.381890622  1  1  1
O  0.881865185  0.881865185  0.881865185  1  1  1
O  0.895777646  0.618048125  0.118103635  1  1  1
O  0.39556058  0.118079437  0.118079437  1  1  1
O  0.395545047  0.116872594  0.618134628  1  1  1
O  0.395545047  0.618134628  0.116872594  1  1  1
O  0.394646153  0.622577564  0.622577564  1  1  1
O  0.895621591  0.118139496  0.118139496  1  1  1
O  0.895777646  0.118103635  0.618048125  1  1  1
O  0.895688723  0.618428431  0.618428431  1  1  1
O  0.604453953  0.883127406  0.381865372  1  1  1
O  0.104310277  0.381571569  0.381571569  1  1  1
O  0.104221354  0.381951875  0.881895365  1  1  1
O  0.104221354  0.881895365  0.381951875  1  1  1
O  0.104378409  0.881860504  0.881860504  1  1  1
O  0.605351847  0.377421436  0.377421436  1  1  1
O  0.604453953  0.381865372  0.883127406  1  1  1
O  0.60443942  0.881919563  0.881919563  1  1  1
O  0.116872594  0.395545047  0.618134628  1  1  1
O  0.118079437  0.39556058  0.118079437  1  1  1
O  0.118139496  0.895621591  0.118139496  1  1  1
O  0.118103635  0.895777646  0.618048125  1  1  1
O  0.618134628  0.395545047  0.116872594  1  1  1
O  0.622577564  0.394646153  0.622577564  1  1  1
O  0.618048125  0.895777646  0.118103635  1  1  1
O  0.618428431  0.895688723  0.618428431  1  1  1
O  0.883127406  0.604453953  0.381865372  1  1  1
O  0.381571569  0.104310277  0.381571569  1  1  1
O  0.381951875  0.104221354  0.881895365  1  1  1
O  0.377421436  0.605351847  0.377421436  1  1  1
O  0.381865372  0.604453953  0.883127406  1  1  1
O  0.881895365  0.104221354  0.381951875  1  1  1
O  0.881860504  0.104378409  0.881860504  1  1  1
O  0.881919563  0.60443942  0.881919563  1  1  1
O  0.622577564  0.622577564  0.394646153  1  1  1
O  0.118079437  0.118079437  0.39556058  1  1  1
O  0.118139496  0.118139496  0.895621591  1  1  1
O  0.116872594  0.618134628  0.395545047  1  1  1
O  0.118103635  0.618048125  0.895777646  1  1  1
O  0.618134628  0.116872594  0.395545047  1  1  1
O  0.618048125  0.118103635  0.895777646  1  1  1
O  0.618428431  0.618428431  0.895688723  1  1  1
O  0.883127406  0.381865372  0.604453953  1  1  1
O  0.381571569  0.381571569  0.104310277  1  1  1
O  0.881860504  0.881860504  0.104378409  1  1  1
O  0.881919563  0.881919563  0.60443942  1  1  1
O  0.377421436  0.377421436  0.605351847  1  1  1
O  0.381951875  0.881895365  0.104221354  1  1  1
O  0.381865372  0.883127406  0.604453953  1  1  1
O  0.881895365  0.381951875  0.104221354  1  1  1

K_POINTS (automatic) 
 1 1 1 0 0 0
`

**Comment by quantumNerd** [comment]
It is now implemented in v0.3.0. Thank you for your suggestion. Please check and let me know in case it doesn't work.
